# Generated by Django 4.2.16 on 2026-08-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_alter_alumnos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
